# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cryptctl < Formula
  desc "CLI for managing secrets to be used with encrypted-secrets"
  homepage "https://github.com/opensecrecy/cryptctl"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/opensecrecy/cryptctl/releases/download/v0.1.0/cryptctl-0.1.0-darwin-arm64.tar.gz"
      sha256 "956e1cad7556ffcbbb5efd958a338d4b1ac6b3e51fab434a71ddea50c590a2c4"

      def install
        bin.install "cryptctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/opensecrecy/cryptctl/releases/download/v0.1.0/cryptctl-0.1.0-darwin-amd64.tar.gz"
      sha256 "e082a23e9ddd5eb525f47790b3761033b375f43720f2bc4faf33e6584d86c38d"

      def install
        bin.install "cryptctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opensecrecy/cryptctl/releases/download/v0.1.0/cryptctl-0.1.0-linux-arm64.tar.gz"
      sha256 "7bb03eec4dcfe18b553ebfe827f759b11277b660002b388b3a36c29f80f064c4"

      def install
        bin.install "cryptctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/opensecrecy/cryptctl/releases/download/v0.1.0/cryptctl-0.1.0-linux-amd64.tar.gz"
      sha256 "4ce37d137bc9e35c15e1c1cd63825ed3450540ab1eb624b570fd2e591f4fefdf"

      def install
        bin.install "cryptctl"
      end
    end
  end
end
